apiVersion: v1
kind: Service
metadata:
  name: superapp-server-service
spec:
  type: ClusterIP
  selector:
    app: superapp-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
