apiVersion: v1
kind: Service
metadata:
  name: superapp-server-service{{ include "global.appendTag" . }}
spec:
  type: ClusterIP
  selector:
    app: superapp-server{{ include "global.appendTag" . }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
