apiVersion: v1
kind: Service
metadata:
  name: blogs-server-service{{ include "global.appendTag" . }}
spec:
  type: ClusterIP
  selector:
    app: blogs-server{{ include "global.appendTag" . }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ include "blogs-server.port" . }}
