apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogs-web-ingress{{ include "global.appendTag" . }}
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.global.topLevelUrl }}
    secretName: linux-vm-southeastasia-2-tls
  rules:
  - host: {{ .Values.global.topLevelUrl }}
    http:
      paths:
      - path: {{ include "blogs-web.rootPath" .}}
        pathType: Prefix
        backend:
          service:
            name: blogs-web-service{{ include "global.appendTag" . }}
            port:
              number: 3000