apiVersion: v1
kind: Service
metadata:
  name: dorms-server-service{{ include "global.appendTag" . }}
spec:
  type: ClusterIP
  selector:
    app: dorms-server{{ include "global.appendTag" . }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ include "dorms-server.port" . }}
