apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorms-server{{ include "global.appendTag" . }}
spec:
  selector:
    matchLabels:
      app: dorms-server{{ include "global.appendTag" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: dorms-server{{ include "global.appendTag" . }}
    spec:
      containers:
        - name: dorms-server
          image: softdev2southeastasia.azurecr.io/dorms-server:{{ .Values.global.revision }}
          ports:
            - containerPort: {{ include "dorms-server.port" . }}
          env:
            {{- template "global.env" . }}
            - name: BASE_WEB_PATH
              value: {{ include "dorms-web.rootPath" . | quote }}
            - name: BASE_SERVER_PATH
              value: {{ include "dorms-server.rootPath" . | quote }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dorms-credential
                  key: JWT_KEY
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: dorms-credential
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: dorms-credential
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dorms-credential
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dorms-credential
                  key: MYSQL_DATABASE

