apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dorms-server-ingress{{ include "global.appendTag" . }}
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.global.topLevelUrl }}
    secretName: linux-vm-southeastasia-2-tls
  rules:
  - host: {{ .Values.global.topLevelUrl }}
    http:
      paths:
      - path: {{ include "dorms-server.rootPath" . }}
        pathType: Prefix
        backend:
          service:
            name: dorms-server-service{{ include "global.appendTag" . }}
            port:
              number: 5000