name: Build and deploy

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

on:
  push:
    branches:
      - "main"
      - "release"
      - "develop"
      - "feature/cicd"
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "main"
      - "release"


jobs:
  superapp_web:
    name: Superapp Website
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set GIT_REF
        run: bash ./env.sh >> "$GITHUB_ENV"

      - name: Login to Azure Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          docker build super-app/web/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-web:${{ github.sha }} --build-arg BASE_SUPERAPP_WEB_PATH=$BASE_SUPERAPP_WEB_PATH
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-web:${{ github.sha }}
        env:
          BASE_SUPERAPP_WEB_PATH: ${{ env.BASE_SUPERAPP_WEB_PATH }}

  superapp_server:
    name: Superapp Server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_REF
        run: bash ./env.sh >> "$GITHUB_ENV"

      - name: Write pull request comment
        uses: actions/github-script@v7
        with:
          script: |
            const { MAIN_URL } = process.env;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Pull request live demo: ${MAIN_URL}`
            });
        env:
          MAIN_URL: ${{ env.MAIN_URL }}
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build super-app/server/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-server:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-server:${{ github.sha }}

  # eats_web:
  #   name: Eats Website
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Azure Login
  #       uses: azure/login@v1.6.1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Set GIT_REF
  #       run: bash ./env.sh >> "$GITHUB_ENV"

  #     - name: Login to Azure Registry
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  #         username: ${{ secrets.REGISTRY_USERNAME }}
  #         password: ${{ secrets.REGISTRY_PASSWORD }}
  #     - name: Build and push image
  #       run: |
  #         docker build hongkrua/web/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/eats-web:${{ github.sha }} --build-arg BASE_EATS_WEB_PATH=$BASE_EATS_WEB_PATH
  #         docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/eats-web:${{ github.sha }}
  #       env:
  #         BASE_EATS_WEB_PATH: ${{ env.BASE_EATS_WEB_PATH }}

  eats_server:
    name: Eats Server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build hongkrua/server/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/eats-server:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/eats-server:${{ github.sha }}

  market_server:
    name: Market Server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_REF
        run: bash ./env.sh >> "$GITHUB_ENV"
        
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build MarketConnect/server/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/markets-server:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/markets-server:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [superapp_web, superapp_server, eats_server, market_server]
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_REF
        run: bash ./env.sh >> "$GITHUB_ENV"

      - name: Deploy to Kubernetes with Helm
        uses: "WyriHaximus/github-action-helm3@v3"
        with:
          exec: helm upgrade --install $GIT_REF ./helm/ --set global.revision=${{ github.sha }} --set-string global.GITHUB_REF=$GIT_REF
          kubeconfig: "${{ secrets.KUBE_CONFIG }}"
        env:
          GIT_REF: ${{ env.GIT_REF }}

