name: Build and deploy superapp website

permissions:
  id-token: write
  contents: read
  actions: read

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build super-app/web/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-web:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/superapp-web:${{ github.sha }}

      - name: Deploy to Kubernetes with Helm
        uses: 'deliverybot/helm@v1'
        with:
          release: 'develop'
          namespace: 'default'
          chart: 'helm'
          helm: 'helm3'
          values: |
            revision: ${{ github.sha }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'